//
//  StyleKit.swift
//  MapTheThings
//
//  Created by Frank Leon Rose on 2017/2/1.
//  Copyright (c) 2017 The Things Network New York. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//



import UIKit

public class StyleKit : NSObject {

    //// Cache

    private struct Cache {
        static let lowSNR: UIColor = UIColor(red: 1.000, green: 0.000, blue: 0.000, alpha: 0.743)
        static let mediumSNR: UIColor = UIColor(red: 1.000, green: 0.660, blue: 0.000, alpha: 0.753)
        static let highSNR: UIColor = UIColor(red: 0.000, green: 1.000, blue: 0.202, alpha: 0.750)
    }

    //// Colors

    public class var lowSNR: UIColor { return Cache.lowSNR }
    public class var mediumSNR: UIColor { return Cache.mediumSNR }
    public class var highSNR: UIColor { return Cache.highSNR }

    //// Drawing Methods

    public class func drawMapSampleMarker( annotationColor: UIColor = UIColor(red: 0.800, green: 0.320, blue: 0.320, alpha: 1.000)) {

        //// Oval Drawing
        let ovalPath = UIBezierPath(ovalIn: CGRect(x: 1, y: 1, width: 14, height: 14))
        annotationColor.setStroke()
        ovalPath.lineWidth = 2
        ovalPath.stroke()
    }

}
